process_data:
  raw_data_dir_path: "/path/to/raw/data/dir"
  processed_data_dir_path: "/path/to/processed/data/dir"

defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 55
    direction: ["minimize", "maximize"]
    study_name: "image-classification"
    storage: null
    n_trials: 3
    n_jobs: 1
    params:
      train_model.lr: range(0.9,1.7,step=0.1)
      train_model.gamma: choice(0.7,0.8,0.9)

train_model:
  setup_mlflow: false
  mlflow_autolog: false
  mlflow_tracking_uri: "mlflow-svc.runai.svc.local"
  mlflow_exp_name: "experiment-01"
  data_dir_path: "/path/to/processed/data/dir"
  no_cuda: true
  no_mps: true
  train_bs: 64
  test_bs: 1000
  lr: 1.0
  gamma: 0.7
  seed: 1111
  epochs: 3
  log_interval: 100
  dry_run: false
  model_checkpoint_interval: 2
  model_checkpoint_dir_path: "/path/to/model/checkpoint"

batch_infer:
  model_path: "./models/model-dir/model.pt"
  input_data_dir: "./data/batch-infer-data-dir"
  use_cuda: false
  use_mps: false
