process_data:
  raw_data_dir_path: "./data/mnist-pngs-data-aisg"
  processed_data_dir_path: "./data/processed/mnist-pngs-data-aisg-processed"

defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 55
    direction: ["minimize", "maximize"]
    study_name: "image-classification"
    storage: null
    n_trials: 3
    n_jobs: 1
    params:
      train_model.lr: range(0.9,1.7,step=0.1)
      train_model.gamma: choice(0.7,0.8,0.9)

train_model:
  setup_mlflow: true
  mlflow_autolog: false
  mlflow_tracking_uri: "./mlruns"
  mlflow_exp_name: "{{cookiecutter.src_package_name_short}}"
  data_dir_path: "./data/processed/mnist-pngs-data-aisg-processed"
  no_cuda: true
  no_mps: true
  train_bs: 64
  test_bs: 1000
  lr: 1.0
  gamma: 0.7
  seed: 1111
  epochs: 3
  log_interval: 100
  dry_run: false
  model_checkpoint_interval: 2
  model_checkpoint_dir_path: "./models/checkpoint"

batch_infer:
  model_path: "./models/model-dir/model.pt"
  input_data_dir: "./data/batch-infer-data-dir"
  output_path: "batch_infer_res.jsonl"
  file_check_glob: "*.png"
  use_cuda: false
  use_mps: false
