apiVersion: run.ai/v2alpha1
kind: TrainingWorkload
metadata:
  name: {{cookiecutter.author_name.replace('_', '-')}}-data-download
  namespace: runai-{{cookiecutter.proj_name.replace('_', '-')}}
spec:
  environment:
    items:
      WORKSPACE_NAME:
        value: {{cookiecutter.author_name.replace('_', '-')}}
  name:
    value: {{cookiecutter.author_name.replace('_', '-')}}-data-download
  image:
    value: alpine
  imagePullPolicy:
    value: IfNotPresent
  command:
    # Change your values here to download other data sources according 
    # to your project needs.
    value: >-
      /bin/sh -c "
      mkdir -p workspaces/$WORKSPACE_NAME/data && 
      cd workspaces/$WORKSPACE_NAME/data &&
      echo Moved to $(pwd) &&
      wget https://storage.googleapis.com/aisg-mlops-pub-data/kapitan-hull/mnist-pngs-data-aisg.zip &&
      unzip mnist-pngs-data-aisg.zip &&
      chown -R 2222:2222 ."
    workingDir:
      value: /{{cookiecutter.proj_name.replace('_', '-')}}-pvc
    cpu:
      value: '0.5'
  cpu:
    value: '0.5'
  cpuLimit:
    value: '0.5'
  memory:
    value: 1G
  memoryLimit:
    value: 1G
  pvcs:
    items:
      pvc-0:
        value: 
          claimName: {{cookiecutter.proj_name.replace('_', '-')}}-pvc
          existingPvc: true
          path: /{{cookiecutter.proj_name.replace('_', '-')}}-pvc
          readOnly: false
          readWriteMany: true
  username:
    value: {{cookiecutter.author_name}}