apiVersion: run.ai/v2alpha1
kind: TrainingWorkload
metadata:
  name: {{cookiecutter.author_name.replace('_', '-')}}-data-prep
  namespace: runai-{{cookiecutter.proj_name.replace('_', '-')}}
spec:
  environment:
    items:
      WORKSPACE_NAME:
        value: {{cookiecutter.author_name.replace('_', '-')}}
  name: 
    value: {{cookiecutter.author_name.replace('_', '-')}}-data-prep
  image:
    value: {{cookiecutter.registry_project_path}}/data-prep:runai-yaml-build
  imagePullPolicy:
    value: Always
  command:
    value: >-
      /bin/bash -c "source activate {{cookiecutter.repo_name}} && python src/process_data.py 
      process_data.raw_data_dir_path=../data/mnist-pngs-data-aisg
      process_data.processed_data_dir_path=../data/processed/mnist-pngs-data-aisg-processed"
  workingDir:
    value: /{{cookiecutter.proj_name.replace('_', '-')}}-pvc/workspaces/{{cookiecutter.author_name.replace('_', '-')}}/{{cookiecutter.repo_name}}
  cpu:
    value: '2'
  cpuLimit:
    value: '2'
  memory:
    value: 4G
  memoryLimit:
    value: 4G
  pvcs:
    items:
      pvc-{{cookiecutter.proj_name.replace('_', '-')}}-pvc:
        value:
          claimName: {{cookiecutter.proj_name.replace('_', '-')}}-pvc
          existingPvc: true
          path: /{{cookiecutter.proj_name.replace('_', '-')}}-pvc
          readOnly: false
          readWriteMany: true
  username:
    value: {{cookiecutter.author_name}}
