apiVersion: run.ai/v2alpha1
kind: TrainingWorkload
metadata:
  name: {{cookiecutter.author_name.replace('_', '-')}}-build-dataprep
  namespace: runai-{{cookiecutter.proj_name.replace('_', '-')}}
spec:
  environment:
    items:
      WORKSPACE_NAME:
        value: <YOUR_HYPHENATED_NAME>
      HARBOR_ROBOT_CREDS_JSON:
        value: SECRET:harbor-credentials,.dockerconfigjson
  name:
    value: {{cookiecutter.author_name.replace('_', '-')}}-build-dataprep
  image: 
    value: gcr.io/kaniko-project/executor:debug
  imagePullPolicy:
    value: Always
  command: 
    value: >- 
      /bin/sh -c 
      "mkdir -p /kaniko/.docker;
      echo $HARBOR_ROBOT_CREDS_JSON > /kaniko/.docker/config.json; 
      /kaniko/executor
      --context .
      --dockerfile ./docker/aiap-dsp-mlops-data-prep.Dockerfile
      --destination {{cookiecutter.registry_project_path}}/data-prep:runai-build"
  workingDir:
    value: /{{cookiecutter.proj_name}}-pvc/workspaces/$WORKSPACE_NAME/{{cookiecutter.repo_name}}
  cpu:
    value: '4'
  cpuLimit:
    value: '4'
  memory:
    value: 6G
  memoryLimit:
    value: 6G
  pvcs:
    items:
      pvc-0:
        value: 
          claimName: {{cookiecutter.proj_name}}-pvc
          existingPvc: false
          path: /{{cookiecutter.proj_name}}-pvc
          readOnly: false
          readWriteMany: true
          size: 1000G
          storageClass: nfs-client
  username:
    value: {{cookiecutter.author_name}}