apiVersion: run.ai/v2alpha1
kind: TrainingWorkload
metadata:
  name: {{cookiecutter.author_name.replace('_', '-')}}-hp-train
  namespace: runai-{{cookiecutter.runai_proj_name.replace('_', '-')}}
spec:
  environment:
    items:
      WORKSPACE_NAME:
        value: <YOUR_HYPHENATED_NAME>
      MLFLOW_TRACKING_URI:
        value: <MLFLOW_TRACKING_URI>
      MLFLOW_EXP_NAME:
        value: {{cookiecutter.author_name}}-{{cookiecutter.repo_name}}
      AWS_ACCESS_KEY_ID:
        value: SECRET:s3-credentials,accessKeyId
      AWS_SECRET_ACCESS_KEY:
        value: SECRET:s3-credentials,secretAccessKey
      MLFLOW_S3_ENDPOINT_URL:
        value: https://necs.nus.edu.sg
      MLFLOW_TRACKING_USERNAME:
        value: SECRET:mlflow-admin-credentials,username
      MLFLOW_TRACKING_PASSWORD:
        value: SECRET:mlflow-admin-credentials,password
  name:
    value: {{cookiecutter.author_name.replace('_', '-')}}-hp-train
  image: 
    value: {{cookiecutter.harbor_registry_project_path}}/model-training:0.1.0
  imagePullPolicy:
    value: Always
  command:
    value: >-
      /bin/bash -c "export MLFLOW_HPTUNING_TAG=$(date +%s) && source activate {{cookiecutter.repo_name}} && python src/train_model.py --multirun
      train_model.data_dir_path=/{{cookiecutter.runai_proj_name}}-pvc/workspaces/$WORKSPACE_NAME/data/processed/mnist-pngs-data-aisg-processed
      train_model.model_checkpoint_dir_path=/{{cookiecutter.runai_proj_name}}-pvc/workspaces/$WORKSPACE_NAME/{{cookiecutter.repo_name}}/models
      train_model.setup_mlflow=true train_model.epochs=3
      train_model.mlflow_tracking_uri=$MLFLOW_TRACKING_URI
      train_model.mlflow_exp_name=$MLFLOW_EXP_NAME"
  workingDir:
    value: /{{cookiecutter.runai_proj_name}}-pvc/workspaces/$WORKSPACE_NAME/{{cookiecutter.repo_name}}
  cpu:
    value: '2'
  cpuLimit:
    value: '2'
  memory:
    value: 4G
  memoryLimit:
    value: 4G
  pvcs:
    items:
      pvc-0:
        value:
          claimName: {{cookiecutter.runai_proj_name}}-pvc
          existingPvc: false
          path: /{{cookiecutter.runai_proj_name}}-pvc
          readOnly: false
          readWriteMany: true
          size: 1000G
          storageClass: nfs-client
  username:
    value: {{cookiecutter.author_name}}