# Site Information
site_name: "{{cookiecutter.project_name}}"
site_url: ""
site_author: "{{cookiecutter.author_name}}"
site_description: >-
  "{{cookiecutter.description}}"

# Repository
repo_name: ""
repo_url: ""
edit_uri: ""

# Copyright
copyright: ""

# Configuration
docs_dir: docs
theme:
  name: material
  logo: aisg-logo.png
  language: en
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - toc.follow
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - scheme: aisg
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  favicon: favicon.svg

# Page Tree
nav:
  - Overview: index.md
  - Settting Up:
    - Prerequisites: setting-up/01-prerequisites.md
    - Preface: setting-up/02-preface.md
    - MLOps Components & Platform: setting-up/03-mlops-components-platform.md
  - Running Locally:
    - Developer Workspace: local/04-dev-wksp.md
    - Virtual Environments: local/05-virtual-env.md
    - Data Storage & Versioning: local/06-data-storage-versioning.md
    - Job Orchestration: local/07-job-orchestration.md
  - Using Docker:
    - Developer Workspace: docker/04-dev-wksp.md
    - Virtual Environments: docker/05-virtual-env.md
    - Data Storage & Versioning: docker/06-data-storage-versioning.md
    - Job Orchestration: docker/07-job-orchestration.md
  - Using RunAI:
    - Developer Workspace: runai/04-dev-wksp.md
    - Virtual Environments: runai/05-virtual-env.md
    - Data Storage & Versioning: runai/06-data-storage-versioning.md
    - Job Orchestration: runai/07-job-orchestration.md
  - Sorting Out the Rest:
    - Deployment: setting-up/08-deployment.md
    - Batch Inferencing: setting-up/09-batch-inferencing.md
    - CI/CD: setting-up/10-cicd.md
    - Documentation: setting-up/11-documentation.md

# Plugins
plugins:
  - search
  - ezlinks
  - termynal
  - minify:
      minify_html: true

# Customisation
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets