setup_mlflow: true
mlflow_autolog: false
mlflow_tracking_uri: "./mlruns"
mlflow_exp_name: "{{cookiecutter.src_package_name_short}}"
mlflow_run_name: "train-model"
data_dir_path: "./data/processed"
# dummy_param1 is used as learning rate
dummy_param1: 1.3
# dummy_param2 is used as a multiplier for batch size
dummy_param2: 0.8
artifact_dir_path: "./models"
resume: false

defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 55
    direction: ["minimize", "maximize"]
    study_name: "base-template"
    storage: null
    n_trials: 3
    n_jobs: 1
    params:
      dummy_param1: range(0.9,1.7,step=0.1)  # learning rate range
      dummy_param2: choice(0.7,0.8,0.9)      # batch size factor options
