setup_mlflow: true
mlflow_autolog: false
mlflow_tracking_uri: "./mlruns"
mlflow_exp_name: "{{cookiecutter.src_package_name_short}}"
mlflow_run_name: "train-model"
data_dir_path: "./data/processed"
artifact_dir_path: "./models"
no_cuda: true
no_mps: true
n_estimators: 100
lr: 0.5
gamma: 1
seed: 1111
epochs: 3
log_interval: 100
dry_run: false
model_checkpoint_interval: 2
model_checkpoint_dir_path: "./models"

defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 55
    direction: ["minimize"]
    study_name: "hdb-resale-process"
    storage: null
    n_trials: 3
    n_jobs: 1
    params:
      n_estimators: range(50, 200, step=10)
      lr: tag(log, interval(0.1, 0.6))
      gamma: choice(0,0.1,0.2,0.3,0.4,0.5)
      max_depth: range(2,20,step=1)