apiVersion: run.ai/v2alpha1
kind: TrainingWorkload
metadata:
  name: {{cookiecutter.author_name.replace('_', '-')}}-train
  namespace: runai-{{cookiecutter.proj_name.replace('_', '-')}}
spec:
  environment:
    items:
      WORKSPACE_NAME:
        value: {{cookiecutter.author_name.replace('_', '-')}}
      MLFLOW_EXP_NAME:
        value: {{cookiecutter.proj_name.replace('_', '-')}}
      MLFLOW_TRACKING_URI:
        value: SECRET:mlflow-credentials,url
      MLFLOW_TRACKING_USERNAME:
        value: SECRET:mlflow-credentials,username
      MLFLOW_TRACKING_PASSWORD:
        value: SECRET:mlflow-credentials,password
  name:
    value: {{cookiecutter.author_name.replace('_', '-')}}-train
  image: 
    value: {{cookiecutter.registry_project_path}}/model-training:runai-yaml-build
  imagePullPolicy:
    value: Always
  command:
    value: >-
      /bin/bash -c "source activate {{cookiecutter.repo_name}} && python src/train_model.py
      data_dir_path=../data/processed/mnist-pngs-data-aisg-processed
      mlflow_tracking_uri=$MLFLOW_TRACKING_URI
      mlflow_exp_name=$MLFLOW_EXP_NAME"
  workingDir:
    value: /{{cookiecutter.proj_name}}-pvc/workspaces/{{cookiecutter.author_name.replace('_', '-')}}/{{cookiecutter.repo_name}}
  cpu:
    value: '2'
  cpuLimit:
    value: '2'
  memory:
    value: 4G
  memoryLimit:
    value: 4G
  pvcs:
    items:
      pvc-{{cookiecutter.proj_name.replace('_', '-')}}-pvc:
        value:
          claimName: {{cookiecutter.proj_name.replace('_', '-')}}-pvc
          existingPvc: true
          path: /{{cookiecutter.proj_name.replace('_', '-')}}-pvc
          readOnly: false
          readWriteMany: true
  username:
    value: {{cookiecutter.author_name}}