name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12.9
      - name: Install dependencies
        run: |
          pip install "cookiecutter>=2.2" unidiff
      - name: Generate template with cookiecutter
        run: |
          cookiecutter --replay-file cookiecutter-ghpages.json -o temp_output .
          ls -al temp_output
      - name: Build and deploy docs
        run: |
          cd temp_output/ghpages
          pip install -r aisg-context/guide-site/mkdocs-requirements.txt
          cd aisg-context/guide-site
          mkdocs gh-deploy --force
