name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.11
      - run: pip install -r mkdocs-requirements.txt
      - run: mkdocs gh-deploy --force
